# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.IntegerField()),
                ('center', models.CharField(max_length=50)),
                ('palette_id', models.IntegerField()),
                ('background_index', models.IntegerField()),
                ('svg', models.FileField(upload_to='maps/')),
            ],
        ),
    ]
