# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_map_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
