# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_printsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='height',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='width',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
