# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 19:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from api.management.commands.seedfonts import Command

def seed_fonts(apps, schema_editor):
    font_command = Command()
    font_command.handle();

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170504_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('files', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.RunPython(seed_fonts),
        migrations.AddField(
            model_name='map',
            name='font',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Font'),
            preserve_default=False,
        ),
    ]
